# Generated by Django 4.1.1 on 2022-10-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_like_delete_category_remove_post_category_like_post_and_more'),
    ]

    operations = [
    ]
